# Generated by Django 3.0.3 on 2020-02-27 14:21

import apps.forumkg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumkg', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=apps.forumkg.models.upload_image_path),
        ),
    ]
